---
verbose: False

diakinone:
  email: 'foo@bar.com'
  password: 'BadPassword'
  api_key_id: 'xxx'
  api_key: 'xxx'
  integrator_token: 'xxxxxxxxxxxx'
  location_id: '12345678-90ab-cdef-1234-567890abcdef'
  thermostat_id: '12345678-90ab-cdef12345-67890abcdef1'
  api_version: 1.0
  api_url_base: 'https://api.daikinskyport.com/'
  make_floats:
    - 'ctInverterFinTemp'
    - 'cspSched'
    - 'hspSched'
    - 'tempIndoor'
    - 'sensorRawTemperature'
  select:
    - 'tempIndoor'
    - 'tempOutdoor'

influxdb:
  username: 'influx_usernamehere'
  password: 'influx_usernamepassword'
  host: 'localhost'
  port: '8086'
  retention_policy: 'autogen'
  db_name: 'db_namehere'

logging:
  logger_name: "daikinone2influx"
  log_config: "/usr/local/daikinone2influx/config/logging.yml"
